
import javax.swing.JOptionPane;

public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        register_user_button = new javax.swing.JButton();
        delete_user_button = new javax.swing.JButton();
        add_content_button = new javax.swing.JButton();
        delete_content_button = new javax.swing.JButton();
        query_user_information = new javax.swing.JButton();
        query_content_button = new javax.swing.JButton();
        query_total_users_button = new javax.swing.JButton();
        lend_content_button = new javax.swing.JButton();
        take_back_content_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        query_total_contents_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/content.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 180));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_user_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        register_user_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register New User.png"))); // NOI18N
        register_user_button.setText("Register new user");
        register_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_user_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(register_user_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        delete_user_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        delete_user_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete User.png"))); // NOI18N
        delete_user_button.setText("Delete user");
        delete_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_user_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_user_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, -1));

        add_content_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add_content_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add New Content.png"))); // NOI18N
        add_content_button.setText("Add new content");
        add_content_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_content_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(add_content_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, -1));

        delete_content_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        delete_content_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete Content.png"))); // NOI18N
        delete_content_button.setText("Delete content");
        delete_content_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_content_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(delete_content_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 190, -1));

        query_user_information.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        query_user_information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Query User Information.png"))); // NOI18N
        query_user_information.setText("Query user information");
        query_user_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_user_informationActionPerformed(evt);
            }
        });
        jPanel2.add(query_user_information, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        query_content_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        query_content_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Query For Content.png"))); // NOI18N
        query_content_button.setText("Query for content");
        query_content_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_content_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(query_content_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 80));

        query_total_users_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        query_total_users_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Query Total Number of Users.png"))); // NOI18N
        query_total_users_button.setText("Query total number of users");
        query_total_users_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_total_users_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(query_total_users_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        lend_content_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lend_content_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lend a Content.png"))); // NOI18N
        lend_content_button.setText("Lend a content");
        lend_content_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lend_content_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(lend_content_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 220, 80));

        take_back_content_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        take_back_content_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Take Back Content.png"))); // NOI18N
        take_back_content_button.setText("Take back content");
        take_back_content_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take_back_content_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(take_back_content_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 260, -1));

        logout_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        logout_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log Out.png"))); // NOI18N
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 210, -1));

        query_total_contents_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        query_total_contents_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question-mark-on-a-circular-black-background.png"))); // NOI18N
        query_total_contents_button.setText("Query total number of contents");
        query_total_contents_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_total_contents_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(query_total_contents_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1040, 350));

        setSize(new java.awt.Dimension(1038, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void register_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_user_buttonActionPerformed
        new RegisterNewUser().setVisible(true);
    }//GEN-LAST:event_register_user_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void delete_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_user_buttonActionPerformed
         new DeleteUser().setVisible(true);
    }//GEN-LAST:event_delete_user_buttonActionPerformed

    private void query_total_users_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_total_users_buttonActionPerformed
        //We are deleting one account from accountlist count because we dont want to count the admin
        int total = Accounts.accountList.size() - 1;
        //Text that will show the information
        String totalText = "There are " + total + " member(s) registered into system";
        //MessageDialog method
        JOptionPane.showMessageDialog(null, totalText);
    }//GEN-LAST:event_query_total_users_buttonActionPerformed

    private void query_user_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_user_informationActionPerformed
        new QueryUserInformation().setVisible(true);
    }//GEN-LAST:event_query_user_informationActionPerformed

    private void add_content_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_content_buttonActionPerformed
        new AddContent().setVisible(true);
    }//GEN-LAST:event_add_content_buttonActionPerformed

    private void delete_content_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_content_buttonActionPerformed
        new DeleteContent().setVisible(true);
    }//GEN-LAST:event_delete_content_buttonActionPerformed

    private void lend_content_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lend_content_buttonActionPerformed
        new LendAContentPanel().setVisible(true);
    }//GEN-LAST:event_lend_content_buttonActionPerformed

    private void take_back_content_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_take_back_content_buttonActionPerformed
        new TakingBackContent().setVisible(true);
    }//GEN-LAST:event_take_back_content_buttonActionPerformed

    private void query_content_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_content_buttonActionPerformed
        new QueryContent().setVisible(true);
    }//GEN-LAST:event_query_content_buttonActionPerformed

    private void query_total_contents_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_total_contents_buttonActionPerformed
        int total = Contents.contentList.size();
        String totalText = "There are " + total + " content(s) registered into system";
        JOptionPane.showMessageDialog(null, totalText);
    }//GEN-LAST:event_query_total_contents_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_content_button;
    private javax.swing.JButton delete_content_button;
    private javax.swing.JButton delete_user_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lend_content_button;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton query_content_button;
    private javax.swing.JButton query_total_contents_button;
    private javax.swing.JButton query_total_users_button;
    private javax.swing.JButton query_user_information;
    private javax.swing.JButton register_user_button;
    private javax.swing.JButton take_back_content_button;
    // End of variables declaration//GEN-END:variables
}
