public class LendAContentPanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public LendAContentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        issue_date = new com.toedter.calendar.JDateChooser();
        due_date = new com.toedter.calendar.JDateChooser();
        contentID_combobox = new javax.swing.JComboBox<>();
        userID_combobox = new javax.swing.JComboBox<>();
        lendcontent_button = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setText("Content ID :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("User ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Issue Date :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Due Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        issue_date.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(issue_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        due_date.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, -1));

        contentID_combobox.setEditable(true);
        contentID_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentID_comboboxActionPerformed(evt);
            }
        });
        jPanel2.add(contentID_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 340, -1));

        userID_combobox.setEditable(true);
        jPanel2.add(userID_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 340, -1));

        lendcontent_button.setText("Lend content");
        lendcontent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendcontent_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(lendcontent_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(520, 292));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contentID_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentID_comboboxActionPerformed
       
    }//GEN-LAST:event_contentID_comboboxActionPerformed

    private void lendcontent_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendcontent_buttonActionPerformed
        //We are getting texts from the comboboxs and dates
        String contentID = contentID_combobox.getSelectedItem().toString();
        String userID = userID_combobox.getSelectedItem().toString();
        String issueDate = issue_date.getDate().toString();
        String dueDate = due_date.getDate().toString();
        //We are putting our String variables into our lendContent method
        Contents.lendContent(contentID, userID, issueDate, dueDate);
        setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_lendcontent_buttonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //When gui show up we are adding every content and account into our comboboxes
        for (String content : Contents.contentList.keySet()){
                contentID_combobox.addItem(content);                                
        }
        
        for (String account : Accounts.accountList.keySet()){
            if (!account.equals("admin")){
                userID_combobox.addItem(account);
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        //When gui is hidden we are cleaning our comboboxes to prevent duplicates
        userID_combobox.removeAllItems();
        contentID_combobox.removeAllItems();
    }//GEN-LAST:event_formComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> contentID_combobox;
    private com.toedter.calendar.JDateChooser due_date;
    private com.toedter.calendar.JDateChooser issue_date;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lendcontent_button;
    private javax.swing.JComboBox<String> userID_combobox;
    // End of variables declaration//GEN-END:variables
}
