/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author batuh
 */
public class RegisterNewUser extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewUser
     */
    public RegisterNewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userID_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        department_combobox = new javax.swing.JComboBox<>();
        fullname_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Password :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("User ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Full Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Department");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel1.add(userID_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, -1));
        jPanel1.add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 270, -1));

        department_combobox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        department_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected", "Mathematics", "English Translation and Interpreting", "Physics", "Psychology", "Sociology", "Architecture", "Industrial Design", "Interior Architecture and Environmental Design", "Textile and Fashion Design", "Visual Communication Design", "Law", "Cinema and Digital Media", "New Media and Communication", "Public Relations and Advertising", "Accounting and Auditing Program", "Business Administration", "Economics", "International Trade and Finance", "Logistics Management", "Political Science and International Relations", "Aerospace Engineering", "Biomedical Engineering", "Civil Engineering", "Computer Engineering", "Electrical and Electronics Engineering", "Food Engineering", "Genetics and Bioengineering", "Industrial Engineering", "Mechanical Engineering", "Mechatronics Engineering", "Software Engineering", "Physiotherapy and Rehabilitation", "Health Management", "Nursing", "Medicine" }));
        jPanel1.add(department_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 270, -1));
        jPanel1.add(fullname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));
        jPanel1.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 270, -1));

        save_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        close_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
       setVisible(false);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        //We are getting text from text fields and combobox
        String userID = userID_field.getText();
        String password = password_field.getText();
        String email = email_field.getText();
        String fullName = fullname_field.getText();
        String department = department_combobox.getSelectedItem().toString();
        //Putting them into our createAccount method
        Accounts.createAccount(userID, password, email, fullName, department);
        
        setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_save_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JComboBox<String> department_combobox;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField fullname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField password_field;
    private javax.swing.JButton save_button;
    private javax.swing.JTextField userID_field;
    // End of variables declaration//GEN-END:variables
}
